version: "3.6"
services:
    test:
        build:
            context: .
            dockerfile: test/Dockerfile
        environment:
            PRIVATE_KEY: '0x0e5b033d597b63a04a434b981855db65b7beb4450033919c4ba99cf1ef8fd2be'
        env_file: ./.env.oracle
        networks:
            quorum-external-net:
            ganache-external-net:
networks: 
    quorum-external-net:
        external: true
    ganache-external-net:
        external: true
