version: "3.6"
services:
  bridge-deploy:
    build: ./contracts
    command: "true"
    env_file: ./.env.deploy
    networks: 
        quorum-external-net:
        ganache-external-net:
networks: 
    quorum-external-net:
        external: true
    ganache-external-net:
        external: true
