version: '2.4'
services:
    rabbit:
        cpus: 0.3
        mem_limit: 500m
        environment: ['RABBITMQ_NODENAME=node@rabbit']
        hostname: rabbit
        image: rabbitmq:3
        restart: unless-stopped
        volumes: []
        networks:
            - oracle-internal-net
    redis:
        cpus: 0.1
        mem_limit: 500m
        command: [redis-server, --appendonly, 'yes']
        hostname: redis
        image: redis:4
        restart: unless-stopped
        volumes: []
        networks:
            - oracle-internal-net 
    bridge_request:
        cpus: 0.1
        mem_limit: 500m
        image: poanetwork/tokenbridge-oracle:latest
        env_file: ./.env.oracle
        environment: 
            - NODE_ENV=production
        restart: unless-stopped
        entrypoint: yarn watcher:signature-request
        networks:
            - quorum-external-net
            - ganache-external-net
            - oracle-internal-net
    bridge_collected:
        cpus: 0.1
        mem_limit: 500m
        image: poanetwork/tokenbridge-oracle:latest
        env_file: ./.env.oracle
        environment: 
            - NODE_ENV=production
        restart: unless-stopped
        entrypoint: yarn watcher:collected-signatures
        networks:
            - quorum-external-net
            - ganache-external-net
            - oracle-internal-net
    bridge_affirmation:
        cpus: 0.1
        mem_limit: 500m
        image: poanetwork/tokenbridge-oracle:latest
        env_file: ./.env.oracle
        environment: 
              - NODE_ENV=production
        restart: unless-stopped
        entrypoint: yarn watcher:affirmation-request
        networks:
           - quorum-external-net
           - ganache-external-net
           - oracle-internal-net
    bridge_senderhome:
        cpus: 0.1
        mem_limit: 500m
        image: poanetwork/tokenbridge-oracle:latest
        env_file: ./.env.oracle
        environment: 
            - NODE_ENV=production
        restart: unless-stopped
        entrypoint: yarn sender:home
        networks:
            - quorum-external-net
            - oracle-internal-net
    bridge_senderforeign:
        cpus: 0.1
        mem_limit: 500m
        image: poanetwork/tokenbridge-oracle:latest
        env_file: ./.env.oracle
        environment: 
            - NODE_ENV=production
        restart: unless-stopped
        entrypoint: yarn sender:foreign
        networks:
            - ganache-external-net
            - oracle-internal-net
networks:
    ganache-external-net:
        external: true
    quorum-external-net:
        external: true
    oracle-internal-net:
