version: "3.8"
services:
  node1:
    restart: "on-failure"
    image: quorum-block-reward:latest
    healthcheck:
      test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    entrypoint:
      - /bin/sh
      - -c
      - |
        DDIR=/qdata/dd
        GENESIS_FILE="$${DDIR}/genesis.json"
        mkdir -p $${DDIR}
        if [ -z "$$(ls -A $${DDIR})" ]; then
          cp -RT /configs $${DDIR}
          mkdir $${DDIR}/geth
          cp /validator_config/nodekey $${DDIR}/geth
        fi
        geth --datadir $${DDIR} init $${GENESIS_FILE}
        geth --config /configs/geth-config.toml --verbosity 5 --gcmode archive --nodekey $${DDIR}/geth/nodekey --mine --minerthreads 1 --allow-insecure-unlock
    hostname: node
    ports:
      - "8545:8545"
    environment:
      PRIVATE_CONFIG: ignore
    networks:
      quorum-external-net:
        aliases:
          - quorum-node1
    volumes:
      - node_vol1:/qdata
      - ./quorum/configs:/configs:ro
      - ./quorum/validators/0:/validator_config:ro
  node2:
    restart: "on-failure"
    image: quorum-block-reward:latest
    healthcheck:
      test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    entrypoint:
      - /bin/sh
      - -c
      - |
        DDIR=/qdata/dd
        GENESIS_FILE="$${DDIR}/genesis.json"
        mkdir -p $${DDIR}
        if [ -z "$$(ls -A $${DDIR})" ]; then
          cp -RT /configs $${DDIR}
          mkdir $${DDIR}/geth
          cp /validator_config/nodekey $${DDIR}/geth
        fi
        geth --datadir $${DDIR} init $${GENESIS_FILE}
        geth --config /configs/geth-config.toml --verbosity 5 --gcmode archive --nodekey $${DDIR}/geth/nodekey --mine --minerthreads 1 --allow-insecure-unlock
    hostname: node
    environment:
      PRIVATE_CONFIG: ignore
    networks:
      quorum-external-net:
        aliases:
          - quorum-node2
    volumes:
      - node_vol2:/qdata
      - ./quorum/configs:/configs:ro
      - ./quorum/validators/1:/validator_config:ro
  cakeshop:
    image: ${CAKESHOP_DOCKER_IMAGE}
    restart: "no"
    healthcheck:
      test: ["CMD", "wget", "--spider", "--proxy=off", "http://localhost:8999/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    entrypoint:
      - /bin/sh
      - -c
      - |
        DDIR=/qdata/cakeshop/local
        mkdir -p $${DDIR}
        cp -RT /configs/cakeshop $${DDIR}
        java -Xms128M -Xmx128M -Dcakeshop.config.dir=/qdata/cakeshop -Dlogging.path=/qdata/logs/cakeshop -jar /opt/cakeshop/cakeshop.war
    hostname: cakeshop
    ports:
      - "8999:8999"
    networks:
      quorum-external-net:
    volumes:
      - cakeshop_vol:/qdata
      - ./quorum/cakeshop:/configs/cakeshop:ro
networks: 
  quorum-external-net:
    external: true
volumes:
  node_vol1:
  node_vol2:
  cakeshop_vol: